// <auto-generated />
namespace WebApiTest4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class readdedtrains4userneeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdedtrains4userneeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191648574_readded-trains-4user-needed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
