// <auto-generated />
namespace WebApiTest4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class readdedtrains5userref : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdedtrains5userref));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191716419_readded-trains-5user-ref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
