// <auto-generated />
namespace WebApiTest4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedexamtypefk3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedexamtypefk3));
        
        string IMigrationMetadata.Id
        {
            get { return "201704290243435_added-exam-type-fk-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
