//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest4.Parsing {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Topics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Topics() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiTest4.Parsing.Topics", typeof(Topics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двоичное кодирование.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комбинаторика.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекурсивные алгоритмы.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адресация в сети Интернет.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычисление количества информации.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгоритмы для исполнителей с циклами и ветвлениями.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск количества путей в графе.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиционные системы счисления.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запросы для поисковых систем.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Множества. Истинность логических выражений.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка массивов и матриц.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблицы истинности логических выражений.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ программ с циклами и ветвлениями.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ программ с циклами и подпрограммами.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамическое программирование.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логические уравнения.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск ошибок в программе с циклами и ветвлениями.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгоритмы обработки массивов.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теория игр. Выигрышные стратегии.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка потока данных.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ информационных моделей.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базы данных. Файловая система.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодирование и декодирование данных. Условие Фано.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгоритмы для исполнителей.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронные таблицы Ссылки Диаграммы.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ программ с циклами.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодирование изображений и звука. Передача данных.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
    }
}
